global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'exporter_vps'
    static_configs:
      - targets: ['exporter_vps:9100']

  - job_name: 'prometheus-ssh-honeypot'
    static_configs:
      - targets: ['prometheus-ssh-honeypot:9100']
